__all__ = ['base_unit',
           'ground_unit',
           'water_unit',
           'air_unit',
           'immobile_unit',
           'construction_unit',
           'tank',
           'jeep',
           'superjeep',
           'anti_armour',
           'battleship',
           'carrier',
           'artillery',
           'fighter',
           'anti_air',
           'bomber',
           'factory',
           'airstrip',
           'shipyard',
           'startflag']
unit_types = {}
